### ISSUE TITLE
Ingredients' width expands when text overflows instead of wrap

### ISSUE THREAD

**Issue by WesTrinhKL** [nicopierson/hotpotato#117]
URL: https://hotpotato-app.herokuapp.com/view/recipe/26

![image](https://user-images.githubusercontent.com/32968155/130517832-3be9758e-04a6-4e4b-aee6-a1b22ec536c3.png)
![image](https://user-images.githubusercontent.com/32968155/130517863-c3fb6da0-7628-41cf-a963-374b2d745732.png)

**Comment by WesTrinhKL** [comment]
seems like the container in recipe details require a max-width since it will expand horizontally (show the horizontal scroll bar) if preparation is extended 
![image](https://user-images.githubusercontent.com/32968155/130518222-1bd009db-20f0-4a92-949d-3537018ed5b0.png)

**Comment by nicopierson** [comment]
Manual testing, great find.
